[tool.poetry]
name = "mephmetrbot"
version = "0.1.0"
description = ""
authors = ["Maxim <clownl3ss@icloud.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.12"
aiogram = "^3.7.0"
poetry-plugin-dotenv = "^2.2.3"

[tool.poetry.scripts]
poetry = 'poetry.console:run'
app = 'mephmetrbot.app:main'

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"